[project]
name = "trader"
version = "0.39.9"
description = "Awesome trader created by socoldlight"
authors = [
    {name = "socoldlight", email = "socoldlight@example.com"},
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "backtrader",
    "matplotlib",
    "prettytable",
    "python-dotenv",
    "fastapi[standard]",
    "pymongo",
    "statsmodels",
    "binance-common>=1.0.0",
    "binance-sdk-spot>=1.0.0",
]

[dependency-groups]
dev = [
    "pytest",
    "coverage",
    "flake8",
    "black",
    "isort",
    "pytest-cov",
    "mypy",
    "gitchangelog",
    "mkdocs",
    "httpx"
]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
trader = "trader.app.main:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
trader = [
    "VERSION",
    "data/*",
]

[tool.setuptools.packages.find]
where = ["src"]
