[tool.poetry]
name = "trader"
version = "0.38.7"
description = "Awesome trader created by socoldlight"
authors = ["socoldlight <socoldlight@example.com>"]
license = "MIT"
readme = "README.md"

packages = [
    { include = "trader", from = "src" }
]
include = [
    { path = "src/trader/VERSION", format = "sdist" },
    { path = "src/trader/VERSION", format = "wheel" },
]

[tool.poetry.dependencies]
python = ">=3.11,<=3.13"
backtrader = "*"
matplotlib = "*"
prettytable = "*"
python-dotenv = "*"
fastapi = {extras = ["standard"], version = "*"}
pymongo = "*"
statsmodels = "*"
binance-common = "^1.0.0"
binance-sdk-spot = "^1.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "*"
coverage = "*"
flake8 = "*"
black = "*"
isort = "*"
pytest-cov = "*"
mypy = "*"
gitchangelog = "*"
mkdocs = "*"
httpx = "*"

[tool.poetry.scripts]
trader = "trader.app.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"